### ISSUE TITLE
NoMethodError: undefined method `pfamily' for nil:NilClass

### ISSUE THREAD

**Issue by FingersKey** [ahoward/macaddr#33]
system: Windows7
ruby-version: ruby 2.3.3p222 (2016-11-21 revision 56859) [i386-mingw32]

irb(main):004:0> Mac.addr
NoMethodError: undefined method `pfamily' for nil:N
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/mac
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/mac
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/mac
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/mac
        from (irb):4
        from C:/Ruby23/bin/irb.cmd:19:in `<main>'

**Comment by caspark** [comment]
Same symptoms here on a tun0 adapter on linux. `ifconfig` output:

```
tun0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          inet addr:172.22.80.221  P-t-P:172.22.80.221  Mask:255.255.255.255
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1350  Metric:1
          RX packets:46170 errors:0 dropped:0 overruns:0 frame:0
          TX packets:36096 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:500 
          RX bytes:46018582 (46.0 MB)  TX bytes:4660177 (4.6 MB)
```

PR #25 would fix it, but it has been open for just over 2 years so I'm not sure it will ever be merged now.
